- name: install LocalStack
  git:
    repo: 'https://github.com/localstack/localstack.git'
    dest: /opt/localstack
    update: no

- script: /usr/local/bin/docker-compose -f /opt/localstack/docker-compose.yml up -d
- script: init.sh
